---
name: Build, publish and release vscode extension
on:
  push:
    branches:
      - ci
    tags:
      - "v*"
jobs:
  publish-vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install -y coreutils git jq npm
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Check tag
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          TAG="${GITHUB_REF##*/}"
          if [ "$GITHUB_REF_TYPE" == "branch" ]; then
            TAG="v0.0.0"
          fi
          checkTag "$TAG"
      - name: Set version
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          setVersion
      - name: Build
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          build
      - name: Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          publish
      - name: Check Publication
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          checkPublication
      - name: Release
        if: github.ref_type == 'tag'
        uses: action-pack/github-release@v2
        with:
          tag: ${{ github.ref }}
          title: "${{ env.EXTENSION_NAME }} v${{ env.EXTENSION_VERSION }}"
          body: |
            `code --install-extension ${{ env.EXTENSION_FQDN }}@${{ env.EXTENSION_VERSION }}`

            **Visual Studio Marketplace**: https://marketplace.visualstudio.com/items?itemName=${{ env.EXTENSION_FQDN }}
