---
name: Build, publish and release vscode extension
on:
  push:
    branches:
      - ci
    tags:
      - "cacdhc_v*"
      - "gvo_v*"
jobs:
  publish-vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Check Initiating User
        if: github.actor != 'JayBeeDe'
        run: |
          echo "::error title=Unauthorized Access::User ${GITHUB_ACTOR} is not authorized."
          exit 1
      - name: Install packages
        run: sudo apt-get install -y git jq npm
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check tag
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          TAG="${GITHUB_REF##*/}"
          if [ "$GITHUB_REF_TYPE" == "branch" ]; then
            TAG="cacdhc_v0.0.1"
          elif !git tag -v "$TAG" > /dev/null 2>&1; then
            echo "::error::Tag '$TAG' is not signed or could not be verified."
            exit 1
          fi
          checkTag "$TAG"
      - name: Set version
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          setVersion
      - name: Build
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          build
      - name: Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          publish
      - name: Check Publication
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/.github/workflows/vscode_marketplace_libs.sh"
          checkPublication
      - name: Release
        if: github.ref_type == 'tag'
        uses: action-pack/github-release@v2
        with:
          tag: ${{ github.ref }}
          title: "${{ env.EXTENSION_SHORT }}_v${{ env.EXTENSION_VERSION }}"
          body: |
            A new release is available for the following vscode extension:
            ${{ env.EXTENSION_NAME }}

            `code --install-extension ${{ env.EXTENSION_FQDN }}@${{ env.EXTENSION_VERSION }}`

            **Visual Studio Marketplace**: https://marketplace.visualstudio.com/items?itemName=${{ env.EXTENSION_FQDN }}
